# Generated by Django 5.2 on 2025-04-06 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_role_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misconduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('factory', models.CharField(max_length=120)),
                ('position', models.CharField(max_length=120)),
                ('worker_pin', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('senden_to_hr', 'Kadrga yuborilgan'), ('unsigned ', 'Buyruq hali imzolanmagan'), ('signed', 'Imzolangan'), ('cancelled', 'Bekor qilingan')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
