# Generated by Django 5.2 on 2025-04-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='misconduct',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misconduct',
            name='status',
            field=models.CharField(choices=[('senden_to_hr', 'Kadrga yuborilgan'), ('unsigned ', 'Buyruq hali imzolanmagan'), ('signed', 'Imzolangan'), ('cancelled', 'Bekor qilingan')], default='senden_to_hr', max_length=50),
        ),
    ]
