# Generated by Django 5.2 on 2025-04-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_misconduct_comment_alter_misconduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misconduct',
            name='status',
            field=models.CharField(choices=[('sent_to_hr', 'Kadrga yuborilgan'), ('unsigned ', 'Buyruq hali imzolanmagan'), ('signed', 'Imzolangan'), ('cancelled', 'Bekor qilingan')], default='sent_to_hr', max_length=50),
        ),
    ]
