# Generated by Django 5.2 on 2025-04-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0003_alter_misconduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='misconduct',
            name='coupon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
