# Generated by Django 5.2 on 2025-04-06 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0004_misconduct_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='misconduct',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='misconduct',
            old_name='edited',
            new_name='edited_at',
        ),
    ]
