# Generated by Django 5.2 on 2025-04-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0005_rename_created_misconduct_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='misconduct',
            name='protocol_path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
