# Generated by Django 5.2 on 2025-04-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0006_misconduct_protocol_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misconduct',
            name='protocol_path',
            field=models.FileField(blank=True, null=True, upload_to='generated/safety/'),
        ),
    ]
