# Generated by Django 5.2 on 2025-04-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0007_alter_misconduct_protocol_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misconduct',
            name='factory',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
