# Generated by Django 5.2 on 2025-04-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0008_alter_misconduct_factory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='misconduct',
            old_name='protocol_path',
            new_name='protocol',
        ),
    ]
