# Generated by Django 5.2 on 2025-04-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0010_misconduct_behest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misconduct',
            name='status',
            field=models.CharField(choices=[('sent_to_hr', 'Kadrga yuborilgan'), ('ready_to_sign', 'Imzolash uchun tayyor'), ('unsigned', 'Buyruq hali imzolanmagan'), ('signed', 'Imzolangan'), ('cancelled', 'Bekor qilingan')], default='sent_to_hr', max_length=50),
        ),
    ]
