# Generated by Django 5.2 on 2025-04-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0011_alter_misconduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misconduct',
            name='status',
            field=models.CharField(choices=[('sent_to_hr', 'Kadrga yuborilgan'), ('ready_to_send', 'Rahbarga yuboish uchun tayyor'), ('waiting_sign', 'Imzolash kutilmoqda'), ('signed', 'Imzolangan'), ('cancelled', 'Bekor qilingan')], default='sent_to_hr', max_length=50),
        ),
    ]
